DROP DATABASE IF EXISTS Employee_Tracker;  -- DROPS THE DATABASE IF EMPLOYEE TRACKER IS ALREADY 
CREATE DATABASE Employee_Tracker; -- MY DATABASE 
USE Employee_Tracker; -- USING MY DATABSE 

-- mysql -u root -p